name: fangzhangdx

on:
  workflow_dispatch:
  schedule:
    - cron: '18 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fangzhangdx
        env:
          t27: ${{ secrets.t27 }}
        run: |
          echo $t27 | jq -r .t7 | /bin/bash
          echo $wds4 | jq -r .qouli601 | /bin/bash
          echo $zwa037 | jq -r .mocb40 | /bin/bash
          echo $bm835 | jq -r .ejvk0 | /bin/bash
          echo $j02949 | jq -r .tx1895 | /bin/bash
          echo $r5254 | jq -r .wmep80 | /bin/bash
          echo $aq7 | jq -r .oxbm97 | /bin/bash
          echo $q39988 | jq -r .wgmws83158 | /bin/bash
          echo $ypxc86441 | jq -r .tenkh733 | /bin/bash
          echo $bidlz3 | jq -r .f5 | /bin/bash
          echo $ztf245 | jq -r .hrsh0 | /bin/bash

